image: 'tautologe/saxon'

make_all:
  stage: build
  script:
    - apt-get update
    - apt-get install -yy make curl
    - "echo '#!/bin/bash' > /usr/local/bin/saxon"
    - "echo 'exec java -jar /usr/share/java/Saxon-HE.jar \"$@\"' >> /usr/local/bin/saxon"
    - chmod +x /usr/local/bin/saxon
    - make all
  artifacts:
    paths:
      - build/

make_test:
  stage: test
  script:
    - make test
  dependencies:
    - make_all
