image: 'registry.gitlab.com/dpkendal/xslisbn'

make_all:
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - build/

make_test:
  stage: test
  script:
    - make test
  dependencies:
    - make_all
